"""
Regression tests for desispec.scripts.tsnr_afterburner.

These tests compare v2 output to a pre-computed fixture generated by v1
(desi_tsnr_afterburner).  All tests in this module are automatically skipped
when the fixture file is absent so that CI environments without DESI data
are unaffected.

To generate fixtures::

    # Run a separately saved original executable on a small test production
    /path/to/original/desi_tsnr_afterburner --prod <testprod> -o <fixture_dir>/v1_exposures.fits \\
        --nights <night>

    # Set environment variable pointing at fixture dir
    export TSNR_AFTERBURNER2_REGRESSION_DIR=<fixture_dir>

The regression test then runs v2 on the same production + nights combination
stored in the fixture metadata and checks that:

- All EXPID values in v1 output also appear in v2 output.
- TSNR2_{ELG,LRG,BGS} agree to within 5% for each matched exposure.
- EFFTIME_SPEC agrees to within 5%.
- Column sets are a superset of v1 columns.
"""

import os
import unittest

import numpy as np
from astropy.table import Table

_FIXTURE_ENV = 'TSNR_AFTERBURNER2_REGRESSION_DIR'
_FIXTURE_DIR = os.environ.get(_FIXTURE_ENV, None)
_SKIP_REASON = (
    'Regression fixtures not available. '
    'Set {} to the directory containing v1 output FITS files to enable.'.format(_FIXTURE_ENV)
)

_V1_FITS = os.path.join(_FIXTURE_DIR, 'v1_exposures.fits') if _FIXTURE_DIR else None
_V2_FITS = os.path.join(_FIXTURE_DIR, 'v2_exposures.fits') if _FIXTURE_DIR else None
_V2_GENERATED = False


def _fixtures_present():
    """Return True when all required fixture files exist."""
    return (
        _FIXTURE_DIR is not None
        and os.path.isdir(_FIXTURE_DIR)
        and _V1_FITS is not None
        and os.path.isfile(_V1_FITS)
    )


def _read_reference(extname):
    """Read modern or historical extension names from the original output."""
    legacy = {'EXPOSURES': 'TSNR2_EXPID', 'FRAMES': 'TSNR2_FRAME'}
    from astropy.io import fits
    with fits.open(_V1_FITS) as hdus:
        extension = extname if extname in hdus else legacy[extname]
    return Table.read(_V1_FITS, hdu=extension)


def _ensure_v2_output():
    """Run the current implementation once per test session, overwriting stale output.

    Reads production and night metadata from the v1 fixture header.
    Searches multiple HDUs for SPECPROD, then falls back to $SPECPROD env var.
    """
    global _V2_GENERATED
    if _V2_GENERATED:
        return

    v1 = _read_reference('EXPOSURES')
    nights = sorted(set(v1['NIGHT'].tolist()))
    nights_arg = ','.join(str(n) for n in nights)

    # SPECPROD: search primary HDU and common extension names, then env var
    from astropy.io.fits import getheader
    specprod = None
    for hdu in (0, 'EXPOSURES', 'TSNR2_EXPID'):
        try:
            specprod = getheader(_V1_FITS, hdu).get('SPECPROD', None)
            if specprod:
                break
        except Exception:
            pass
    if not specprod:
        specprod = os.environ.get('SPECPROD', None)

    # build argv for v2
    argv = ['-o', _V2_FITS, '--nights', nights_arg, '--overwrite',
            '--expids', ','.join(str(e) for e in v1['EXPID'])]
    if specprod is not None:
        argv += ['--prod', specprod]

    from desispec.scripts.tsnr_afterburner import main
    rc = main(argv)
    if rc != 0:
        raise RuntimeError('v2 main() returned error code {}'.format(rc))
    _V2_GENERATED = True


@unittest.skipUnless(_fixtures_present(), _SKIP_REASON)
class TestRegressionVsV1Exposures(unittest.TestCase):
    """Compare v2 EXPOSURES table against v1 TSNR2_EXPID table."""

    @classmethod
    def setUpClass(cls):
        _ensure_v2_output()
        try:
            cls.v1 = _read_reference('EXPOSURES')
        except Exception as e:
            raise RuntimeError('Cannot read v1 HDU TSNR2_EXPID from {}: {}'.format(_V1_FITS, e))
        try:
            cls.v2 = Table.read(_V2_FITS, hdu='EXPOSURES')
        except Exception as e:
            raise RuntimeError('Cannot read v2 HDU EXPOSURES from {}: {}'.format(_V2_FITS, e))

        # index by EXPID for quick lookup
        cls.v1_idx = {int(e): i for i, e in enumerate(cls.v1['EXPID'])}
        cls.v2_idx = {int(e): i for i, e in enumerate(cls.v2['EXPID'])}

    def test_v1_expids_present_in_v2(self):
        """Every EXPID in v1 should also appear in v2."""
        missing = [e for e in self.v1_idx if e not in self.v2_idx]
        self.assertEqual(missing, [],
                         '{} EXPIDs from v1 missing in v2: {}'.format(len(missing), missing[:10]))

    def test_column_superset(self):
        """v2 should have at least all columns present in v1."""
        v1_cols = set(self.v1.colnames)
        v2_cols = set(self.v2.colnames)
        missing = v1_cols - v2_cols
        self.assertEqual(missing, set(), 'v2 missing columns from v1: {}'.format(missing))

    def test_tsnr2_elg_agreement(self):
        """TSNR2_ELG must agree between v1 and v2 within 5%."""
        self._check_column_agreement('TSNR2_ELG', rtol=0.05)

    def test_tsnr2_lrg_agreement(self):
        """TSNR2_LRG must agree between v1 and v2 within 5%."""
        self._check_column_agreement('TSNR2_LRG', rtol=0.05)

    def test_tsnr2_bgs_agreement(self):
        """TSNR2_BGS must agree between v1 and v2 within 5%."""
        self._check_column_agreement('TSNR2_BGS', rtol=0.05)

    def test_efftime_spec_agreement(self):
        """EFFTIME_SPEC must agree within 5%."""
        self._check_column_agreement('EFFTIME_SPEC', rtol=0.05)

    def test_exptime_agreement(self):
        """EXPTIME must agree exactly (or within floating-point rounding)."""
        self._check_column_agreement('EXPTIME', rtol=0.001)

    def _check_column_agreement(self, col, rtol=0.05):
        """Compare a column between v1 and v2 for matched EXPIDs.

        Args:
            col: str, column name.
            rtol: float, relative tolerance for comparison.
        """
        if col not in self.v1.colnames:
            self.skipTest('{} not in v1'.format(col))
        if col not in self.v2.colnames:
            self.fail('{} not in v2'.format(col))

        mismatches = []
        for expid, i1 in self.v1_idx.items():
            if expid not in self.v2_idx:
                continue
            i2 = self.v2_idx[expid]
            v1_val = float(self.v1[col][i1])
            v2_val = float(self.v2[col][i2])
            self.assertTrue(np.isfinite(v1_val) and np.isfinite(v2_val),
                            'Non-finite {} for EXPID {}'.format(col, expid))
            # skip if both are effectively zero
            if abs(v1_val) < 1e-6 and abs(v2_val) < 1e-6:
                continue
            denom = max(abs(v1_val), 1e-6)
            if abs(v1_val - v2_val) / denom > rtol:
                mismatches.append((expid, v1_val, v2_val))

        if mismatches:
            frac = len(mismatches) / max(len(self.v1_idx), 1)
            self.fail(
                '{} agreement failures for {} ({:.1%} of exposures): '
                'first 5 (expid, v1, v2) = {}'.format(
                    len(mismatches), col, frac, mismatches[:5]))


@unittest.skipUnless(_fixtures_present(), _SKIP_REASON)
class TestRegressionVsV1Frames(unittest.TestCase):
    """Compare v2 FRAMES table against v1 TSNR2_FRAME table."""

    @classmethod
    def setUpClass(cls):
        _ensure_v2_output()
        try:
            cls.v1 = _read_reference('FRAMES')
        except Exception as e:
            raise RuntimeError('Cannot read v1 HDU TSNR2_FRAME from {}: {}'.format(_V1_FITS, e))
        try:
            cls.v2 = Table.read(_V2_FITS, hdu='FRAMES')
        except Exception as e:
            raise RuntimeError('Cannot read v2 HDU FRAMES from {}: {}'.format(_V2_FITS, e))

    def test_frames_row_count_comparable(self):
        """v2 should have at least as many FRAMES rows as v1 (more if bad exps injected)."""
        self.assertGreaterEqual(len(self.v2), len(self.v1),
                                'v2 FRAMES has fewer rows than v1 ({} < {})'.format(
                                    len(self.v2), len(self.v1)))

    def test_frames_has_camera_column(self):
        """FRAMES table must have a CAMERA column."""
        self.assertIn('CAMERA', self.v2.colnames)

    def test_frames_tsnr2_nonzero(self):
        """At least half of FRAMES rows should have TSNR2_ELG > 0."""
        if 'TSNR2_ELG' not in self.v2.colnames:
            self.skipTest('TSNR2_ELG not in v2 FRAMES')
        nonzero = np.sum(self.v2['TSNR2_ELG'] > 0)
        self.assertGreater(nonzero, len(self.v2) // 2)


if __name__ == '__main__':
    unittest.main()
