.. code-block:: console

    usage: desi_pipe_status <command> [options]

    Where supported commands are:
        all   Overview of the whole production.
       step   Details about a particular pipeline step.
       task   Explore a particular task.

    Explore DESI pipeline status

    positional arguments:
      command     Subcommand to run

    optional arguments:
      -h, --help  show this help message and exit
