#%Module1.0
# The first line of this file tells Modules that this is a module file.
# DO NOT ALTER IT!
#
# ABOUT THIS FILE
#
# This file is designed to be processed by Python.  Specifically, this file
# will be read into a string, and the .format() method will be applied to it.
# This file is not a valid module file on its own.
#
# METADATA AND DOCUMENTATION SECTION
#
# This function is part of the Modules help system.  You can modify
# the second line if needed, but most products should
# leave this alone.
#
proc ModulesHelp {{ }} {{
    global product version
    puts stderr "This module adds $product/$version to your environment."
}}
#
# These variables are used below.  The product variable should be set to
# the name of the product and never changed.  The version variable will
# be set at install time, so it should be left alone.  The conflict line
# prevents multiple versions from being loaded simultaneously.  Do not
# change it.
#
set product {name}
set version {version}
conflict $product
#
# The line below is another part of the Modules help system.  You can
# modify the part in quotes if you really need to, but most products should
# leave this alone.
#
module-whatis "Sets up $product/$version in your environment."
#
# DEPENDENCIES SECTION
#
# If your product requires other software to function, that should be declared
# here.  There are two types of dependencies: mandatory and optional.
# A mandatory dependency is a module load command followed by a prereq
# command.  An optional dependency is not followed by a prereq statement.
#
# module load desiutil
# prereq desiutil
#
# ENVIRONMENT SECTION
#
# The PRODUCT_ROOT and PRODUCT_DIR variables are used to set other
# environment variables but are not exported to the actual environment.
# If you are not working at NERSC, but still want to use Modules, you
# will need to set the DESI_PRODUCT_ROOT environment variable
#
if {{[info exists env(DESI_PRODUCT_ROOT)]}} {{
    set code_root $env(DESI_PRODUCT_ROOT)/code
}} else {{
    set code_root {product_root}
}}
set PRODUCT_DIR $code_root/$product/$version
#
# This line creates an environment variable pointing to the install
# directory of your product.
#
setenv [string toupper $product] $PRODUCT_DIR
#
# The lines below set various other environment variables.  They assume the
# template product layout.  These will be set or commented as needed by the
# desiInstall script.
#
{needs_bin}prepend-path PATH $PRODUCT_DIR/bin
{needs_python}prepend-path PYTHONPATH $PRODUCT_DIR/lib/{pyversion}/site-packages
{needs_trunk_py}prepend-path PYTHONPATH $PRODUCT_DIR{trunk_py_dir}
{needs_ld_lib}prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
{needs_idl}prepend-path IDL_PATH +$PRODUCT_DIR/pro
#
# Add any non-standard Module code below this point.
#
setenv DESI_SPECTRO_CALIB $env(DESI_ROOT)/spectro/desi_spectro_calib/trunk
setenv DESI_SPECTRO_DARK $env(DESI_ROOT)/spectro/desi_spectro_dark/latest

# for MPI+multiprocessing coordination
setenv MPICH_GNI_FORK_MODE FULLCOPY
setenv KMP_AFFINITY disabled

# for zmtl generation running QuasarNP
# OLD:
# setenv QN_MODEL_FILE $env(DESI_ROOT)/target/catalogs/lya/qn_models/qn_train_coadd_indtrain_0_0_boss10.h5
# After desispec PR #2230 and QuasarNP PR #7:
# setenv QN_MODEL_FILE $env(DESI_ROOT)/science/lya/qn_models/desi/qn_train_desi_guadalupe_linear.h5
# 2024-06-18: reverting to previous weights while debugging new ones
setenv QN_MODEL_FILE $env(DESI_ROOT)/target/catalogs/lya/qn_models/qn_train_coadd_indtrain_0_0_boss10.h5

# possible future SQuEZE afterburner
setenv SQ_MODEL_FILE $env(DESI_ROOT)/target/catalogs/lya/sq_models/BOSS_train_64plates_model.json

